<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HomeBase.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeBase.Database\HomeBase.Database.csproj" />
  </ItemGroup>
</Project>
