// <auto-generated />
using System;
using System.Collections.Generic;
using HomeBase.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeBase.Database.Migrations
{
    [DbContext(typeof(HomeBaseDbContext))]
    [Migration("20260918060437_AssetServiceDates")]
    partial class AssetServiceDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeBase.Database.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("CurrentValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("current_value");

                    b.Property<DateOnly?>("DisposedAt")
                        .HasColumnType("date")
                        .HasColumnName("disposed_at");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextServiceAt")
                        .HasColumnType("date")
                        .HasColumnName("next_service_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<long?>("PurchaseItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_item_id");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("purchase_price");

                    b.Property<DateOnly?>("PurchasedAt")
                        .HasColumnType("date")
                        .HasColumnName("purchased_at");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<int?>("ServiceIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("service_interval_days");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("WarrantyUntil")
                        .HasColumnType("date")
                        .HasColumnName("warranty_until");

                    b.HasKey("Id")
                        .HasName("pk_asset");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_asset_category_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_asset_location_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_asset_product_id");

                    b.HasIndex("PurchaseItemId")
                        .HasDatabaseName("ix_asset_purchase_item_id");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_asset_serial_number");

                    b.ToTable("asset", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.AssetDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_asset_document");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_document_asset_id");

                    b.ToTable("asset_document", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("icon");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_category_parent_id_name");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.MealPlanEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cooked_at");

                    b.Property<string>("FreeText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("free_text");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date")
                        .HasColumnName("plan_date");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("servings");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("slot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_meal_plan_entry");

                    b.HasIndex("PlanDate")
                        .HasDatabaseName("ix_meal_plan_entry_plan_date");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_meal_plan_entry_recipe_id");

                    b.ToTable("meal_plan_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_plan_entry_recipe_or_text", "recipe_id IS NOT NULL OR free_text IS NOT NULL");
                        });
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("base_unit");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DefaultLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("default_location_id");

                    b.Property<int?>("DefaultShelfLifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_shelf_life_days");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsFood")
                        .HasColumnType("boolean")
                        .HasColumnName("is_food");

                    b.Property<decimal?>("MinStockBase")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("min_stock_base");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OffId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("off_id");

                    b.Property<decimal>("PackageSize")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasDefaultValue(1m)
                        .HasColumnName("package_size");

                    b.Property<decimal?>("PieceWeightBase")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("piece_weight_base");

                    b.Property<decimal?>("TargetStockBase")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("target_stock_base");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_id");

                    b.HasIndex("DefaultLocationId")
                        .HasDatabaseName("ix_product_default_location_id");

                    b.HasIndex("Gtin")
                        .IsUnique()
                        .HasDatabaseName("ix_product_gtin");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_product_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.ProductAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("raw_text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<int>("TimesSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("times_seen");

                    b.HasKey("Id")
                        .HasName("pk_product_alias");

                    b.HasIndex("NormalizedText")
                        .HasDatabaseName("ix_product_alias_normalized_text");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_alias_product_id");

                    b.HasIndex("StoreId", "NormalizedText")
                        .IsUnique()
                        .HasDatabaseName("ix_product_alias_store_id_normalized_text");

                    b.ToTable("product_alias", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("EUR")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<string>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<string>("ReceiptFile")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("receipt_file");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<decimal?>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_purchase");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_external_id");

                    b.HasIndex("PurchasedAt")
                        .HasDatabaseName("ix_purchase_purchased_at");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_purchase_store_id");

                    b.ToTable("purchase", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.PurchaseItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin");

                    b.Property<bool>("IsPromo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_promo");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("line_type");

                    b.Property<float?>("MatchConfidence")
                        .HasColumnType("real")
                        .HasColumnName("match_confidence");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("match_status");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_item_id");

                    b.Property<decimal?>("PricePerBaseUnit")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(14, 6)
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("price_per_base_unit")
                        .HasComputedColumnSql("line_total / NULLIF(quantity_base, 0)", true);

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("QuantityBase")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_base");

                    b.Property<string>("RawText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("raw_text");

                    b.Property<int?>("SuggestedProductId")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_product_id");

                    b.Property<decimal?>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(14, 6)
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_item");

                    b.HasIndex("ParentItemId")
                        .HasDatabaseName("ix_purchase_item_parent_item_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_item_product_id");

                    b.HasIndex("SuggestedProductId")
                        .HasDatabaseName("ix_purchase_item_suggested_product_id");

                    b.HasIndex("PurchaseId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_item_purchase_id_line_no");

                    b.ToTable("purchase_item", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CookMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("PrepMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_minutes");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("servings");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.HasKey("Id")
                        .HasName("pk_recipe");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_recipe_name");

                    b.ToTable("recipe", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FreeText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("free_text");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_optional");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("QuantityBase")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_base");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_recipe_ingredient");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_recipe_ingredient_product_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_ingredient_recipe_id");

                    b.ToTable("recipe_ingredient", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipe_ingredient_product_or_text", "product_id IS NOT NULL OR free_text IS NOT NULL");
                        });
                });

            modelBuilder.Entity("HomeBase.Database.Entities.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list");

                    b.ToTable("shopping_list", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.ShoppingListItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("added_by");

                    b.Property<DateTimeOffset?>("BoughtAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bought_at");

                    b.Property<string>("FreeText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("free_text");

                    b.Property<int>("ListId")
                        .HasColumnType("integer")
                        .HasColumnName("list_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<long?>("PurchaseItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_item_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_price");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list_item");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_shopping_list_item_product_id");

                    b.HasIndex("PurchaseItemId")
                        .HasDatabaseName("ix_shopping_list_item_purchase_item_id");

                    b.HasIndex("ListId", "Status", "AddedBy")
                        .HasDatabaseName("ix_shopping_list_item_list_id_status_added_by");

                    b.ToTable("shopping_list_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_shopping_list_item_product_or_text", "product_id IS NOT NULL OR free_text IS NOT NULL");
                        });
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StockLot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("BestBefore")
                        .HasColumnType("date")
                        .HasColumnName("best_before");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<long?>("PurchaseItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_item_id");

                    b.Property<decimal>("QuantityBase")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_base");

                    b.HasKey("Id")
                        .HasName("pk_stock_lot");

                    b.HasIndex("BestBefore")
                        .HasDatabaseName("ix_stock_lot_best_before")
                        .HasFilter("quantity_base > 0");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_stock_lot_location_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stock_lot_product_id")
                        .HasFilter("quantity_base > 0");

                    b.HasIndex("PurchaseItemId")
                        .HasDatabaseName("ix_stock_lot_purchase_item_id");

                    b.ToTable("stock_lot", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("LotId")
                        .HasColumnType("bigint")
                        .HasColumnName("lot_id");

                    b.Property<long?>("MealPlanEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("meal_plan_entry_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_delta");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stock_movement");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_stock_movement_lot_id");

                    b.HasIndex("MealPlanEntryId")
                        .HasDatabaseName("ix_stock_movement_meal_plan_entry_id");

                    b.HasIndex("ProductId", "OccurredAt")
                        .HasDatabaseName("ix_stock_movement_product_id_occurred_at");

                    b.ToTable("stock_movement", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_storage_location");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_storage_location_parent_id");

                    b.ToTable("storage_location", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Chain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chain");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_store");

                    b.ToTable("store", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Views.DepositBalance", b =>
                {
                    b.Property<decimal?>("OpenDeposit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("open_deposit");

                    b.ToTable((string)null);

                    b.ToView("v_deposit_balance", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Views.EffectiveLine", b =>
                {
                    b.Property<decimal?>("EffectivePricePerBaseUnit")
                        .HasPrecision(14, 6)
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("effective_price_per_base_unit");

                    b.Property<decimal>("EffectiveTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("effective_total");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("IsPromo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_promo");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<long>("PurchaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_id");

                    b.Property<decimal?>("QuantityBase")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_base");

                    b.ToTable((string)null);

                    b.ToView("v_effective_line", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Views.MonthlySpend", b =>
                {
                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("Month")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("month");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.ToTable((string)null);

                    b.ToView("v_monthly_spend", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Views.PricePoint", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<bool>("IsPromo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_promo");

                    b.Property<decimal?>("PrevPrice")
                        .HasPrecision(14, 6)
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("prev_price");

                    b.Property<decimal?>("PricePerBaseUnit")
                        .HasPrecision(14, 6)
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("price_per_base_unit");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.ToTable((string)null);

                    b.ToView("v_price_history", (string)null);
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Asset", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_asset_categories_category_id");

                    b.HasOne("HomeBase.Database.Entities.StorageLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asset_storage_locations_location_id");

                    b.HasOne("HomeBase.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asset_products_product_id");

                    b.HasOne("HomeBase.Database.Entities.PurchaseItem", "PurchaseItem")
                        .WithMany()
                        .HasForeignKey("PurchaseItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asset_purchase_items_purchase_item_id");

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("PurchaseItem");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.AssetDocument", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Asset", "Asset")
                        .WithMany("Documents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_document_asset_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Category", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_category_category_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.MealPlanEntry", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meal_plan_entry_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Product", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_category_category_id");

                    b.HasOne("HomeBase.Database.Entities.StorageLocation", "DefaultLocation")
                        .WithMany()
                        .HasForeignKey("DefaultLocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_storage_locations_default_location_id");

                    b.Navigation("Category");

                    b.Navigation("DefaultLocation");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.ProductAlias", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Product", "Product")
                        .WithMany("Aliases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_alias_products_product_id");

                    b.HasOne("HomeBase.Database.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_product_alias_stores_store_id");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Purchase", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_purchase_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.PurchaseItem", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.PurchaseItem", "ParentItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_purchase_item_purchase_item_parent_item_id");

                    b.HasOne("HomeBase.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_purchase_item_product_product_id");

                    b.HasOne("HomeBase.Database.Entities.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_item_purchase_purchase_id");

                    b.HasOne("HomeBase.Database.Entities.Product", "SuggestedProduct")
                        .WithMany()
                        .HasForeignKey("SuggestedProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_purchase_item_product_suggested_product_id");

                    b.Navigation("ParentItem");

                    b.Navigation("Product");

                    b.Navigation("Purchase");

                    b.Navigation("SuggestedProduct");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recipe_ingredient_product_product_id");

                    b.HasOne("HomeBase.Database.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredient_recipe_recipe_id");

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.ShoppingList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_item_shopping_list_list_id");

                    b.HasOne("HomeBase.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_shopping_list_item_product_product_id");

                    b.HasOne("HomeBase.Database.Entities.PurchaseItem", "PurchaseItem")
                        .WithMany()
                        .HasForeignKey("PurchaseItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shopping_list_item_purchase_item_purchase_item_id");

                    b.Navigation("List");

                    b.Navigation("Product");

                    b.Navigation("PurchaseItem");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StockLot", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.StorageLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_lot_storage_locations_location_id");

                    b.HasOne("HomeBase.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_lot_product_product_id");

                    b.HasOne("HomeBase.Database.Entities.PurchaseItem", "PurchaseItem")
                        .WithMany()
                        .HasForeignKey("PurchaseItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_lot_purchase_item_purchase_item_id");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("PurchaseItem");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StockMovement", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.StockLot", "Lot")
                        .WithMany("Movements")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_movement_stock_lot_lot_id");

                    b.HasOne("HomeBase.Database.Entities.MealPlanEntry", "MealPlanEntry")
                        .WithMany("Movements")
                        .HasForeignKey("MealPlanEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stock_movement_meal_plan_entry_meal_plan_entry_id");

                    b.HasOne("HomeBase.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movement_product_product_id");

                    b.Navigation("Lot");

                    b.Navigation("MealPlanEntry");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StorageLocation", b =>
                {
                    b.HasOne("HomeBase.Database.Entities.StorageLocation", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_storage_location_storage_location_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Asset", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.MealPlanEntry", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Product", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Purchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.PurchaseItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StockLot", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("HomeBase.Database.Entities.StorageLocation", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
