<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup Label="User Interface">
        <PackageVersion Include="MudBlazor" Version="9.9.0" />
    </ItemGroup>

    <ItemGroup Label="Entity Framework Core">
        <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup Label="Testing">
        <PackageVersion Include="coverlet.collector" Version="10.0.1" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageVersion Include="NSubstitute" Version="6.2.0" />
        <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

</Project>
